// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Prisma 5 does not use this file.
// DATABASE_URL is configured via the .env file.
export {};
